version: "3.8"

services:
  backend:
    build: ./backend
    command: --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    restart: always
  
  frontend:
    build: ./frontend
    command: start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/code
    restart: always
