version: "3.8"

services:
  backend:
    container_name: backend-dev
    build: ./backend
    command: --reload
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    restart: always
  
  frontend:
    container_name: frontend-dev
    build: ./frontend
    command: start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
    env_file:
      - ./frontend/.env.dev
    restart: always
